GCN:
  drop_out: 0.4
  hiddim: 32
  gnn_learning_rate: 0.018
  arch_learning_rate: 0.047
  arch_learning_rate_min: 0.005
  gnn_weight_decay: 0.0001
  arch_weight_decay: 0.001
  aug_M: 5
  max_lambda: 1.0
  conf: 0.44
  tem: 0.14
  reg_loss: 'kl'
  mean_acc: 0.8363
GraphSAGE:
  drop_out: 0.5
  hiddim: 64
  gnn_learning_rate: 0.018
  arch_learning_rate: 0.048
  arch_learning_rate_min: 0.0065
  gnn_weight_decay: 0.0001
  arch_weight_decay: 0.001
  aug_M: 6
  max_lambda: 1.0
  conf: 0.4
  tem: 0.67
  reg_loss: 'l2'
  mean_acc: 0.8339
GAT:
  drop_out: 0.1
  hiddim: 32
  gnn_learning_rate: 0.02
  arch_learning_rate: 0.017
  arch_learning_rate_min: 0.0045
  gnn_weight_decay: 0.001
  arch_weight_decay: 0.0005
  aug_M: 5
  max_lambda: 1.0
  conf: 0.13
  tem: 0.11
  reg_loss: 'kl'
  mean_acc: 0.8385