GCN:
  drop_out: 0.4
  hiddim: 128
  gnn_learning_rate: 0.044
  arch_learning_rate: 0.041
  arch_learning_rate_min: 0.0075
  weight_decay: 0.0001
  arch_weight_decay: 0.0005
  aug_M: 5
  max_lambda: 0.2
  conf: 0.17
  tem: 0.39
  reg_loss: 'l2'
  mean_f1: 0.6428
GraphSAGE:
  drop_out: 0.5
  hiddim: 128
  gnn_learning_rate: 0.042
  arch_learning_rate: 0.043
  arch_learning_rate_min: 0.0095
  weight_decay: 0.0001
  arch_weight_decay: 0.005
  aug_M: 7
  max_lambda: 0.3
  conf: 0.4
  tem: 0.24
  reg_loss: 'kl'
  mean_f1: 0.6401
GAT:
  drop_out: 0.45
  hiddim: 128
  gnn_learning_rate: 0.02
  arch_learning_rate: 0.033
  arch_learning_rate_min: 0.004
  weight_decay: 0.0001
  arch_weight_decay: 0.001
  aug_M: 4
  max_lambda: 0.15
  conf: 0.43
  tem: 0.44
  reg_loss: 'l2'
  mean_f1: 0.6164