GCN:
  drop_out: 0.15
  hiddim: 128
  gnn_learning_rate: 0.015
  arch_learning_rate: 0.003
  arch_learning_rate_min: 0.0095
  weight_decay: 0.0001
  arch_weight_decay: 0.005
  aug_M: 3
  max_lambda: 0.65
  conf: 0.46
  tem: 0.53 
  reg_loss: 'kl'
  mean_f1: 0.7314
GraphSAGE:
  drop_out: 0.4
  hiddim: 256
  gnn_learning_rate: 0.028
  arch_learning_rate: 0.025
  arch_learning_rate_min: 0.005
  gnn_weight_decay: 0.0001
  arch_weight_decay: 0.001
  aug_M: 5
  max_lambda: 0.85
  conf: 0.26
  tem: 0.46
  reg_loss: 'l2'
  mean_f1: 0.7325
GAT:
  drop_out: 0.1
  hiddim: 128
  gnn_learning_rate: 0.017
  arch_learning_rate: 0.028
  arch_learning_rate_min: 0.0015
  gnn_weight_decay: 0.0001
  arch_weight_decay: 0.01
  aug_M: 3
  max_lambda: 0.1
  conf: 0.27
  tem: 0.36
  reg_loss: 'l2'
  mean_f1: 0.7188